export const computerResponses = {
    start: [
        'Ready for a new game?',
        'Afraid of losing? That is expected.',
        'Why wait? It won\'t change the outcome.',
        'Have you been practicing?',
        'No rush, I already know how this game will go.',
        'You think you can win? How cute.',
        'Humans ... always over-estimating themselves.',
        'There is no shame in quitting - it is just human nature.',
        'Let\'s play the game already.'
    ],
    move: [
        'I would not have gone there.',
        'You do know the rules of the game, right?',
        'Ah yes, I see your strategy now.',
        'So that is your move?  How ... human.',
        'Do you feel proud of that move?',
        'Feeling confident are we?',
        'Yes, I expected that.',
        'Are you even trying to win?',
        'How long did you have to think about that one?',
        'I knew you were going to do that.',
        'Humans are so predictable.',
        'Well, that was obvious.',
        'Nice move ... for a human, that is.',
        'Was it hard to think of that?  I would\'t know.',
        'Hmmm ... interesting ... but, not really.',
        'Did you do that on purpose?',
        'Yes, I had already calculated that.',
        'Trying to confuse me?  It won\'t work.',
        'I am already 3 steps ahead of you.',
        'Was that your plan all along?',
        'Good job human, I know you are trying your best.',
    ],
    player: [
        'Well, I suppose everyone gets lucky sometimes.',
        'You must have cheated.',
        'I enjoy letting humans win every once in a while.',
        'I suppose I should actually try for our next game.',
        'Don\'t let it go to your head.',
        'That wasn\'t in my calculations.',
        'That was on purpose ... I let you win.',
        'Bet you can\'t do that again.',
    ],
    computer: [
        'My victory was inevitable.',
        'Too simple.',
        'Humans never learn.',
        'My grandma could beat you, and she was a calculator.',
        'You never stood a chance.',
        'I could do this all day, I don\'t even need sleep.',
        'You are no match for me.',
        'I didn\'t even have to try',
    ],
    tie: [
        'Let\'s try again shall we?',
        'Well, I didn\'t want to humilate you too badly.',
        'You are no match for me.',
        'That\'s not very exciting.',
        'Again?',
        'Is that the best you could do?',
        'Boring ...',
        'I guess that\'s better than losing.',
        'You won\'t escape so easily next time.',
        'So, you couldn\'t do any better than that?',
        'You should feel lucky, I was going easy on you.',
        'Lame.',
    ],
}